In [2]:
# Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [4]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero.
import numpy as np
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))


Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


In [15]:
#Create an identity matrix of dimension 4-by-4
#Eg:
#[[1. 0. 0. 0.]
#[0. 1. 0. 0.]
#[0. 0. 1. 0.]
#[0. 0. 0. 1.]]

import numpy as np
x = np. zeros((4, 4))
x[::2, 1::2] = 1.
x[1::2, ::2] = 1.
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [23]:
# Convert a 1-D array to a 3-D array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Convert 1D Numpy array to a 3D array with 2 matrices of shape 2X3
arr_3d = np.reshape(arr, (2, 2, 3))
print('3D Numpy array:')
print(arr_3d)

3D Numpy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [71]:
# Convert all the elements of a numpy array from float to integer datatype

numpy.ndarray.astype()
numpy.ndarray.astype(dtype)
print(float_array)
int_array = float_array.astype(int)
print(int_array)

NameError: name 'numpy' is not defined

In [28]:
# Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.38890043 0.21431587 0.97427386 0.9270033  0.3409726  0.97814348
  0.71829335 0.25437    0.20794042 0.23557051]
 [0.16064003 0.55607306 0.12402821 0.74983672 0.90027514 0.19076389
  0.12309685 0.93185304 0.43579419 0.60302439]
 [0.75154947 0.95711124 0.28437455 0.04202649 0.41894736 0.50793886
  0.91320299 0.53684949 0.38054294 0.76505804]
 [0.28901788 0.27437066 0.42193839 0.25137309 0.59374413 0.36532482
  0.62731049 0.27709228 0.0406191  0.11674199]
 [0.58821232 0.27581099 0.6369086  0.37596451 0.23657274 0.61508738
  0.35031143 0.04401287 0.61292703 0.83330845]
 [0.8095374  0.99503134 0.28830211 0.45936547 0.13033824 0.80945532
  0.57491911 0.37292221 0.33695544 0.9132985 ]
 [0.00704414 0.36644957 0.44036409 0.65585225 0.03346012 0.09286048
  0.37044093 0.72358768 0.75288453 0.05268496]
 [0.26073905 0.0566824  0.88855832 0.22641784 0.79648178 0.32884362
  0.92572345 0.47979431 0.14658687 0.86025129]
 [0.05490436 0.10625235 0.92333051 0.42775436 0.46523089 0.09302

In [29]:
# Create a random vector of size 30 and find the mean value 
x = np.random.random(30)
x.mean()

0.5479734091752732

In [32]:
# Create a 2d array with 1 on the border and 0 inside
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
# How to add a border (filled with 0's) around an existing array?
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.array([1, 2, 3, 4])
np.diag(x)
print(x)

[1 2 3 4]


In [38]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
x = np.zeros((8, 8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [39]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(100, (6, 7, 8))


(1, 5, 4)

In [40]:
# Create a checkerboard 8x8 matrix using the tile function
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [42]:
# Normalize a 5x5 random matrix
x = np.random.random(size=(5, 5))
x_mean = np.mean(x)
x_var = np.var(x)
x_norm = (x - x_mean) / np.sqrt(x_var)
print(x)

[[0.93559937 0.50073005 0.65068161 0.51840621 0.90904018]
 [0.39236003 0.24600223 0.3530693  0.97681433 0.14112096]
 [0.26888743 0.97430736 0.40369858 0.59638075 0.54646535]
 [0.29936323 0.43643494 0.48808471 0.25375092 0.70144299]
 [0.2572249  0.09068361 0.42101615 0.26396435 0.73332368]]


In [44]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-44-aebc25ca7804>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [45]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [47]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [49]:
#How to round away from zero a float array ?
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([10., -7., -3., -6., -9., -2.,  6., -4.,  4.,  6.])

In [50]:
# How to find common values between two arrays?
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

In [51]:
# How to get the dates of yesterday, today and tomorrow?
today = np.datetime64('today', 'D')
yesterday = today - np.datetime64(1, 'D')
tomorrow = today + np.datetime64(1, 'D')

UFuncTypeError: ufunc 'add' cannot use operands with types dtype('<M8[D]') and dtype('<M8[D]')

In [53]:
# How to get all the dates corresponding to the month of July 2016?
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [54]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)


array([-1.5, -1.5, -1.5])

In [55]:
# Extract the integer part of a random array of positive numbers using 4 different methods
x = np.random.uniform(-10, +10, 10)
x.astype(np.int32)
np.trunc(x)

array([-8., -4., -5., -8., -5.,  9.,  4., -2., -1., -5.])

In [57]:
# Create a 5x5 matrix with row values ranging from 0 to 4
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [58]:
# Consider a generator function that generates 10 integers and use it to build an array
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [59]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.linspace(start=0, stop=11, num=10, endpoint=False)


array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [61]:
# Create a random vector of size 10 and sort it
x = np.random.random(size=10)
x.sort()
print(x)

[0.2112167  0.52593201 0.71347284 0.72236335 0.81471976 0.81688541
 0.82813877 0.869738   0.97318101 0.97873915]


In [62]:
# How to sum a small array faster than np.sum?
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

5.999088287353516
3.000020980834961


In [63]:
# Consider two random array A and B, check if they are equal
A = np.arange(10)
B = np.arange(10)
np.array_equal(A, B)

True

In [64]:
# Make an array immutable (read-only)
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1   

ValueError: assignment destination is read-only

In [65]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.92872497 0.67645388 0.52617918 0.6836635  0.86829675 0.65149075
 1.18387151 0.90052948 0.64588481 0.15956474]
[1.15523252 0.73591913 0.21378401 1.29473501 0.24344182 0.80155279
 0.61776565 0.53092887 0.65935955 0.08426993]


In [67]:
# Create random vector of size 10 and replace the maximum value by 0
x = np.random.random(10)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
print(x)

[0.38525773 0.42946805 0.65400225 0.04920513 0.         0.
 0.74235106 0.18499599 0.68312263 0.40029634]


In [69]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [70]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 1.49923709e+06, -8.72780715e+05, -9.32341547e+04,
         3.10786849e+05, -7.49623595e+06],
       [-3.74373801e+06,  1.33138474e+05,  1.14760266e+05,
         1.58179248e+08,  1.07480079e+05],
       [-3.62457581e+06, -4.39086975e+06, -7.12049839e+07,
         7.81410190e+05, -2.93009684e+05],
       [-8.37968706e+03, -1.66791612e+06, -3.04364735e+06,
         2.64339157e+07,  7.41412855e+05],
       [-7.29743195e+04,  1.61442243e+06, -1.65280213e+08,
        -6.39489648e+03, -2.29731687e+07]])