# 1. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [2]:
import numpy as np
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 2.Compute a matrix rank

In [40]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print (rank)

10


# 3.How to find the most frequent value in an array?

In [4]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[2 5 9 2 2 5 1 0 7 1 0 4 0 5 4 2 6 8 8 9 4 3 6 2 2 0 2 4 8 1 9 4 5 1 0 5 2
 9 8 6 0 6 3 5 9 4 2 3 0 9]
rank: 2


# 4.Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [35]:
Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 1 4]
   [3 0 4]
   [2 3 3]]

  [[1 4 2]
   [0 4 3]
   [3 3 3]]

  [[4 2 2]
   [4 3 3]
   [3 3 2]]

  [[2 2 0]
   [3 3 1]
   [3 2 0]]]


 [[[3 0 4]
   [2 3 3]
   [2 1 4]]

  [[0 4 3]
   [3 3 3]
   [1 4 4]]

  [[4 3 3]
   [3 3 2]
   [4 4 2]]

  [[3 3 1]
   [3 2 0]
   [4 2 0]]]


 [[[2 3 3]
   [2 1 4]
   [1 1 3]]

  [[3 3 3]
   [1 4 4]
   [1 3 2]]

  [[3 3 2]
   [4 4 2]
   [3 2 2]]

  [[3 2 0]
   [4 2 0]
   [2 2 0]]]


 [[[2 1 4]
   [1 1 3]
   [0 1 3]]

  [[1 4 4]
   [1 3 2]
   [1 3 1]]

  [[4 4 2]
   [3 2 2]
   [3 1 2]]

  [[4 2 0]
   [2 2 0]
   [1 2 1]]]]


# 5.Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [53]:
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  6 11  9  6]
 [ 6  4  3 12 10]
 [11  3  6 42  7]
 [ 9 12 42  5 10]
 [ 6 10  7 10  0]]


# 6.Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [7]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


# 7.Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [8]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


# 8.How to implement the Game of Life using numpy arrays?

In [34]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
Z

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# 9.How to get the n largest values of an array

In [31]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


# 10.Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [11]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 11.How to create a record array from a regular array?

In [30]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

# 12.Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [51]:
import numpy as np
x = np.random.rand(47)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.2 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.57 µs ± 113 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
4.97 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 13.Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [29]:
import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)


[0 1 2 5 6]


# 14.Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [28]:
import numpy as np
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 1 0]
 [0 3 3]
 [1 3 4]
 [3 2 4]
 [2 3 0]
 [3 4 0]
 [0 2 0]
 [3 4 4]
 [0 3 4]
 [0 2 0]]
[[3 1 0]
 [0 3 3]
 [1 3 4]
 [3 2 4]
 [2 3 0]
 [3 4 0]
 [0 2 0]
 [3 4 4]
 [0 3 4]
 [0 2 0]]


# 15.Convert a vector of ints into a matrix binary representation

In [27]:
import numpy as np
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 16. Given a two dimensional array, how to extract unique rows?



In [26]:
import numpy as np
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


# 17.Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function



In [25]:
import numpy as np
A= np.arange(3)
B =  np.arange(12).reshape(3,4)
print (A)

[0 1 2]


# 18.Considering a path described by two vectors (X,Y), how to sample it using equidistant samples ?



In [39]:
import numpy as np
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
dr

array([0.1       , 0.10099422, 0.10295387, 0.10582533, 0.10953691,
       0.11400658, 0.11914907, 0.12488128, 0.1311259 , 0.13781329,
       0.14488215, 0.15227936, 0.15995938, 0.16788341, 0.17601848,
       0.18433667, 0.19281427, 0.20143115, 0.21017019, 0.21901677,
       0.22795836, 0.2369842 , 0.24608504, 0.25525285, 0.26448065,
       0.2737624 , 0.28309278, 0.29246713, 0.30188136, 0.31133186,
       0.32081541, 0.33032917, 0.33987061, 0.34943745, 0.35902767,
       0.36863944, 0.37827112, 0.38792122, 0.39758841, 0.40727146,
       0.41696928, 0.42668085, 0.43640526, 0.44614167, 0.4558893 ,
       0.46564746, 0.4754155 , 0.48519281, 0.49497885, 0.50477312,
       0.51457514, 0.52438447, 0.53420072, 0.54402351, 0.55385249,
       0.56368734, 0.57352776, 0.58337346, 0.59322418, 0.60307968,
       0.61293972, 0.62280409, 0.63267259, 0.64254503, 0.65242122,
       0.662301  , 0.67218422, 0.68207071, 0.69196035, 0.701853  ,
       0.71174853, 0.72164683, 0.73154777, 0.74145127, 0.75135

# 19.Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.



In [23]:
import numpy as np
X = np.asarray([[1.0, 0.0, 3.0, 8.0],

[2.0, 0.0, 1.0, 1.0],

[1.5, 2.5, 1.0, 0.0]])

n = 4

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)

M &= (X.sum(axis=-1) == n)

print(X[M])

[[2. 0. 1. 1.]]


# 20.Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [22]:
import numpy as np
X = np.random.randn(100) # random 1D array

N = 1000 # number of bootstrap samples

idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confint = np.percentile(means, [2.5, 97.5])

print(confint)

[-0.24079943  0.18839968]
